-- Additive pricing expansion. Legacy service values and existing order snapshots remain untouched.
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'FLYER_STANDARD';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'CATALOG_DISTRIBUTION';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'BROCHURE_MAGAZINE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'VOUCHER_CARD';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'POSTCARD_INVITATION';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'EVENT_INVITATION';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'COMMUNITY_PUBLICATION';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'MENU_DELIVERY_CARD';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'PRODUCT_SAMPLING';

CREATE TYPE "WeightClass" AS ENUM ('LIGHT', 'STANDARD', 'MEDIUM', 'HEAVY', 'CUSTOM');
CREATE TYPE "AreaDifficulty" AS ENUM ('NORMAL', 'MIXED', 'LOW_DENSITY', 'RURAL', 'HARD');

ALTER TABLE "Order"
  ADD COLUMN "weightClass" "WeightClass" NOT NULL DEFAULT 'LIGHT',
  ADD COLUMN "weightInGrams" INTEGER,
  ADD COLUMN "areaDifficulty" "AreaDifficulty" NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN "productDetails" JSONB;

ALTER TABLE "PricingRule"
  ADD COLUMN "pricingVersion" TEXT NOT NULL DEFAULT 'service-pricing-v1',
  ADD COLUMN "configurationVersion" TEXT NOT NULL DEFAULT 'pricing-config-v1',
  ADD COLUMN "validFrom" TIMESTAMP(3),
  ADD COLUMN "validTo" TIMESTAMP(3),
  ADD COLUMN "notes" TEXT;
